version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      # - echo Installing source NPM dependencies...
      - npm install
  post_build:
    commands:
      - echo Build completed `date`
artifacts:
  files:
    - '**/*'
